language: php
sudo: false
matrix:
    fast_finish: true
    include:
        - php: hhvm
          env: 
           - WAFFLE_CHECK=true
        - php: hhvm
        - php: hhvm-nightly
          env:
           - WAFFLE_CHECK=true
        - php: hhvm-nightly
    allow_failures:
        - php: hhvm-nightly

install:
    - composer self-update
    - composer install

before_script:
    - if [[ $WAFFLE_CHECK='true' ]]; then hh_server --daemon $TRAVIS_BUILD_DIR; fi

script:
    - if [[ $WAFFLE_CHECK='true' ]]; then composer check; fi
    - composer test
